export const QuestionsContextActions = {
    GET_QUESTIONS_START: "GET_QUESTION_START",
    GET_QUESTIONS_SUCCESS: "GET_QUESTION_SUCCESS",
    GET_QUESTIONS_FAIL: "GET_QUESTION_FAIL",

    PUT_QUESTIONS: "PUT_QUESTION",
    POST_QUESTIONS: "POST_QUESTION"
}